# Generated by Django 5.2.6 on 2025-10-25 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_invoice_id', models.CharField(max_length=120, unique=True)),
                ('stripe_session_id', models.CharField(max_length=120)),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='mxn', max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('hosted_invoice_url', models.URLField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='usuarios.usuario')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
