# Generated by Django 5.2.6 on 2025-10-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='currency',
            field=models.CharField(default='usd', max_length=10),
        ),
    ]
