# Generated by Django 5.2.7 on 2025-10-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_alter_factura_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='stock_processed',
            field=models.BooleanField(default=False),
        ),
    ]
