# Generated by Django 5.2.7 on 2025-10-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
