# Generated by Django 5.2.7 on 2025-10-26 17:30

import django.db.models.deletion
from django.db import migrations, models


def copy_role_forward(apps, schema_editor):
    Usuario = apps.get_model("usuarios", "Usuario")
    for usuario in Usuario.objects.all():
        if usuario.rol_permiso_id:
            usuario.rol_id = usuario.rol_permiso.rol_id
            usuario.save(update_fields=["rol"])


def copy_role_backward(apps, schema_editor):
    Usuario = apps.get_model("usuarios", "Usuario")
    for usuario in Usuario.objects.all():
        usuario.rol_id = None
        usuario.save(update_fields=["rol"])


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='usuarios.rol'),
        ),
        migrations.RunPython(copy_role_forward, copy_role_backward),
        migrations.RemoveField(
            model_name='usuario',
            name='rol_permiso',
        ),
    ]
