# Generated by Django 5.2.7 on 2025-10-26 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_remove_usuario_rol_permiso_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=100)),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar'), ('DESCARGAR', 'Descargar'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('objeto_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_entries', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Bitacora',
                'verbose_name_plural': 'Bitacora',
                'ordering': ['-creado_en'],
            },
        ),
    ]
