# Generated by Django 5.2.7 on 2025-10-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacoraentry',
            name='entidad',
        ),
        migrations.RemoveField(
            model_name='bitacoraentry',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='bitacoraentry',
            name='objeto_id',
        ),
        migrations.RemoveField(
            model_name='bitacoraentry',
            name='metadata',
        ),
        migrations.AlterField(
            model_name='bitacoraentry',
            name='accion',
            field=models.CharField(max_length=255),
        ),
    ]
